on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: CI Build
        run: |
          script/bootstrap
          script/cibuild

